[package]
name = "rustusb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.4"
usb-ids = "1.2024.4"
clap = { version = "4.5.9", features = ["derive"] }